/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface LitheumPrivateBCOERC20Interface extends Interface {
  functions: {
    LitheumERC20TokenAddress: TypedFunctionDescription<{
      encode([]: []): string;
    }>;

    addToWhitelist: TypedFunctionDescription<{
      encode([_address, limit]: [string, BigNumberish]): string;
    }>;

    allowance: TypedFunctionDescription<{
      encode([owner, spender]: [string, string]): string;
    }>;

    approve: TypedFunctionDescription<{
      encode([spender, value]: [string, BigNumberish]): string;
    }>;

    balanceOf: TypedFunctionDescription<{
      encode([account]: [string]): string;
    }>;

    burn: TypedFunctionDescription<{
      encode([amount]: [BigNumberish]): string;
    }>;

    decimals: TypedFunctionDescription<{ encode([]: []): string }>;

    getEstimatedSwapAmount: TypedFunctionDescription<{
      encode([usdtAmount]: [BigNumberish]): string;
    }>;

    getPLTHBalance: TypedFunctionDescription<{ encode([]: []): string }>;

    getStaticPrice: TypedFunctionDescription<{ encode([]: []): string }>;

    getUSDTBalance: TypedFunctionDescription<{ encode([]: []): string }>;

    getWhitelistWithLimit: TypedFunctionDescription<{
      encode([address_]: [string]): string;
    }>;

    isAddressInWhitelist: TypedFunctionDescription<{
      encode([_address]: [string]): string;
    }>;

    isConvertible: TypedFunctionDescription<{ encode([]: []): string }>;

    isOwner: TypedFunctionDescription<{ encode([]: []): string }>;

    launchSAFT: TypedFunctionDescription<{ encode([]: []): string }>;

    modifyLimit: TypedFunctionDescription<{
      encode([_address, limit]: [string, BigNumberish]): string;
    }>;

    name: TypedFunctionDescription<{ encode([]: []): string }>;

    removeFromWhitelist: TypedFunctionDescription<{
      encode([_address]: [string]): string;
    }>;

    setLitheumERC20TokenAddress: TypedFunctionDescription<{
      encode([LitheumERC20TokenAddress_]: [string]): string;
    }>;

    setStaticPrice: TypedFunctionDescription<{
      encode([staticPrice_]: [BigNumberish]): string;
    }>;

    staticPrice: TypedFunctionDescription<{ encode([]: []): string }>;

    staticSwap: TypedFunctionDescription<{
      encode([usdtAmount]: [BigNumberish]): string;
    }>;

    symbol: TypedFunctionDescription<{ encode([]: []): string }>;

    totalSupply: TypedFunctionDescription<{ encode([]: []): string }>;

    transfer: TypedFunctionDescription<{
      encode([recipient, amount]: [string, BigNumberish]): string;
    }>;

    transferFrom: TypedFunctionDescription<{
      encode([sender_, recipient_, amount_]: [
        string,
        string,
        BigNumberish
      ]): string;
    }>;

    usdtContract: TypedFunctionDescription<{ encode([]: []): string }>;

    withdraw: TypedFunctionDescription<{
      encode([usdtAmount]: [BigNumberish]): string;
    }>;
  };

  events: {
    Approval: TypedEventDescription<{
      encodeTopics([owner, spender, value]: [
        string | null,
        string | null,
        null
      ]): string[];
    }>;

    Transfer: TypedEventDescription<{
      encodeTopics([from, to, value]: [
        string | null,
        string | null,
        null
      ]): string[];
    }>;
  };
}

export class LitheumPrivateBCOERC20 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): LitheumPrivateBCOERC20;
  attach(addressOrName: string): LitheumPrivateBCOERC20;
  deployed(): Promise<LitheumPrivateBCOERC20>;

  on(event: EventFilter | string, listener: Listener): LitheumPrivateBCOERC20;
  once(event: EventFilter | string, listener: Listener): LitheumPrivateBCOERC20;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): LitheumPrivateBCOERC20;
  removeAllListeners(eventName: EventFilter | string): LitheumPrivateBCOERC20;
  removeListener(eventName: any, listener: Listener): LitheumPrivateBCOERC20;

  interface: LitheumPrivateBCOERC20Interface;

  functions: {
    LitheumERC20TokenAddress(): Promise<string>;

    addToWhitelist(
      _address: string,
      limit: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    allowance(owner: string, spender: string): Promise<BigNumber>;

    approve(
      spender: string,
      value: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    balanceOf(account: string): Promise<BigNumber>;

    burn(
      amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    decimals(): Promise<number>;

    getEstimatedSwapAmount(usdtAmount: BigNumberish): Promise<BigNumber>;

    getPLTHBalance(): Promise<BigNumber>;

    getStaticPrice(): Promise<BigNumber>;

    getUSDTBalance(): Promise<BigNumber>;

    getWhitelistWithLimit(address_: string): Promise<BigNumber>;

    isAddressInWhitelist(_address: string): Promise<boolean>;

    isConvertible(): Promise<boolean>;

    isOwner(): Promise<boolean>;

    launchSAFT(overrides?: TransactionOverrides): Promise<ContractTransaction>;

    modifyLimit(
      _address: string,
      limit: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    name(): Promise<string>;

    removeFromWhitelist(
      _address: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setLitheumERC20TokenAddress(
      LitheumERC20TokenAddress_: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setStaticPrice(
      staticPrice_: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    staticPrice(): Promise<BigNumber>;

    staticSwap(
      usdtAmount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    symbol(): Promise<string>;

    totalSupply(): Promise<BigNumber>;

    transfer(
      recipient: string,
      amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    transferFrom(
      sender_: string,
      recipient_: string,
      amount_: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    usdtContract(): Promise<string>;

    withdraw(
      usdtAmount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  LitheumERC20TokenAddress(): Promise<string>;

  addToWhitelist(
    _address: string,
    limit: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  allowance(owner: string, spender: string): Promise<BigNumber>;

  approve(
    spender: string,
    value: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  balanceOf(account: string): Promise<BigNumber>;

  burn(
    amount: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  decimals(): Promise<number>;

  getEstimatedSwapAmount(usdtAmount: BigNumberish): Promise<BigNumber>;

  getPLTHBalance(): Promise<BigNumber>;

  getStaticPrice(): Promise<BigNumber>;

  getUSDTBalance(): Promise<BigNumber>;

  getWhitelistWithLimit(address_: string): Promise<BigNumber>;

  isAddressInWhitelist(_address: string): Promise<boolean>;

  isConvertible(): Promise<boolean>;

  isOwner(): Promise<boolean>;

  launchSAFT(overrides?: TransactionOverrides): Promise<ContractTransaction>;

  modifyLimit(
    _address: string,
    limit: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  name(): Promise<string>;

  removeFromWhitelist(
    _address: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  setLitheumERC20TokenAddress(
    LitheumERC20TokenAddress_: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  setStaticPrice(
    staticPrice_: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  staticPrice(): Promise<BigNumber>;

  staticSwap(
    usdtAmount: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  symbol(): Promise<string>;

  totalSupply(): Promise<BigNumber>;

  transfer(
    recipient: string,
    amount: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  transferFrom(
    sender_: string,
    recipient_: string,
    amount_: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  usdtContract(): Promise<string>;

  withdraw(
    usdtAmount: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {
    Approval(
      owner: string | null,
      spender: string | null,
      value: null
    ): EventFilter;

    Transfer(from: string | null, to: string | null, value: null): EventFilter;
  };

  estimate: {
    LitheumERC20TokenAddress(): Promise<BigNumber>;

    addToWhitelist(_address: string, limit: BigNumberish): Promise<BigNumber>;

    allowance(owner: string, spender: string): Promise<BigNumber>;

    approve(spender: string, value: BigNumberish): Promise<BigNumber>;

    balanceOf(account: string): Promise<BigNumber>;

    burn(amount: BigNumberish): Promise<BigNumber>;

    decimals(): Promise<BigNumber>;

    getEstimatedSwapAmount(usdtAmount: BigNumberish): Promise<BigNumber>;

    getPLTHBalance(): Promise<BigNumber>;

    getStaticPrice(): Promise<BigNumber>;

    getUSDTBalance(): Promise<BigNumber>;

    getWhitelistWithLimit(address_: string): Promise<BigNumber>;

    isAddressInWhitelist(_address: string): Promise<BigNumber>;

    isConvertible(): Promise<BigNumber>;

    isOwner(): Promise<BigNumber>;

    launchSAFT(): Promise<BigNumber>;

    modifyLimit(_address: string, limit: BigNumberish): Promise<BigNumber>;

    name(): Promise<BigNumber>;

    removeFromWhitelist(_address: string): Promise<BigNumber>;

    setLitheumERC20TokenAddress(
      LitheumERC20TokenAddress_: string
    ): Promise<BigNumber>;

    setStaticPrice(staticPrice_: BigNumberish): Promise<BigNumber>;

    staticPrice(): Promise<BigNumber>;

    staticSwap(usdtAmount: BigNumberish): Promise<BigNumber>;

    symbol(): Promise<BigNumber>;

    totalSupply(): Promise<BigNumber>;

    transfer(recipient: string, amount: BigNumberish): Promise<BigNumber>;

    transferFrom(
      sender_: string,
      recipient_: string,
      amount_: BigNumberish
    ): Promise<BigNumber>;

    usdtContract(): Promise<BigNumber>;

    withdraw(usdtAmount: BigNumberish): Promise<BigNumber>;
  };
}
